---
- hosts: all

  vars_prompt:
    - name: "ip_do_servidor"
      prompt: "Digite o ip do Servidor à ser reabilitado no Big Ip"
      private: no
    - name: "ambiente" 
      prompt: "Digite o nome do ambiente envolvido: dev, inside ou dmz" 

  vars:
    provider:
      transport: cli
      user: admin
      password: senhatemp
      server: "{{ inventory_hostname }}"
      server_port: 22
      #ssh_keyfile: ./config/netsec_testes_infra.pem
      validate_certs: False

  tasks:
      - name: Run single command - provider-cli
        bigip_command:
          commands:
            - modify ltm node "{{ ip_do_servidor }}" state user-up
          provider: "{{ provider }}"
        register: result
        delegate_to: localhost
